server:
  port: 8070

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # SC 渠道配置 - 拼团对接渠道值、回调通知
    group-buy-market:
      api-url: http://127.0.0.1:8091
      notify-url: http://127.0.0.1:8070/api/v1/alipay/group_buy_notify
      source: s01
      chanel: c01

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# 数据库配置；启动时配置数据库资源信息
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://106.52.179.221:13306/s-pay-mall-ddd-market?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

  # RabbitMQ
  rabbitmq:
    addresses: 106.52.179.221
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1 # 每次投递n个消息，消费完在投递n个
    template:
      delivery-mode: persistent # 确保全局默认设置为持久化（可选）
    # 消息配置
    config:
      producer:
        # 主题配置
        topic_order_pay_success:
          # 绑定交换机
          exchange: s_pay_mall_exchange
          # 消费主题
          routing_key: topic.order_pay_success
          # 消费队列
          queue: s_pay_mall_queue_2_order_pay_success
      consumer:
        # 消费 topic 主题，team_success
        topic_team_success:
          # 绑定交换机 - 消息提供者的交换机
          exchange: group_buy_market_exchange
          # 消息主题
          routing_key: topic.team_success
          # 消费队列 - 每个系统有自己的消费队列
          queue: s_pay_mall_queue_2_topic_team_success
        # 主题配置
        topic_order_pay_success:
          # 绑定交换机
          exchange: s_pay_mall_exchange
          # 消费主题
          routing_key: topic.order_pay_success
          # 消费队列
          queue: s_pay_mall_queue_2_order_pay_success

# MyBatis 配置【如需使用记得打开】
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 微信公众号对接
weixin:
  config:
    originalid: gh_380175aa5ca9
    token: b8b6
    app-id: wxd1aaca7aa60142d2
    app-secret: 2b07c84787f2e3323c4d6fdfd4aa1083
    template_id: 1SZJScoWX0Pzwa--okRptvWq6E68nvbqc9KPvWBdZwQ

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000163646623
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDAPD6tIf7Rg3KiHQ9oa2VYptrb2f+iKJHdKZHQk/+1kewVjKtAkUDTbuk2lLqPnbAsWnCBT5cbs61xrGeP6WHXicLIHT7NBlhQwKy4VUUfILiPD5tRdUlKfsrqosBuvMHYwm0qAh1w4FRjRza0elO/NSD9qdB4ysKzBBbNDVuzmTULH6F+/LwvidAHlJIdKTFaJcqMkTTAJrOjR5zAhyfvCdQcjehxUiid7rKQ0rmQsYINYzn68goj7WA1JeWOwO/gAW2asqmOqo2rP0gbDLKvN3RiLuBeMZ1YvHMJy2gcVj/e+FJoaHBfnMRq/hNk8Y92dLiBd2+UccTPq6D+y1QRAgMBAAECggEAAxa0txltu7YN+HbZEYdwOG1t5Mxq5BMczN3nHt/R4vv2PB5nfgEXdo44pwzatoYFF6FYX2uE9Qf9CG+JtnE8hjcLbyWxJaAteRavb8LG+ooPDRVmHHfy9oR1BDIbP2w+/RmaoWspR/ACyxmQ0nOItvDGl+zLkbVITZIKP78wMwGDBkbPREs7CWltAPLLgRXvHPT5DXXU/SnMhvA65DpLQ0laR8KMewxp+TKz5xSGz4khHmXtQTmGjphIq86rR4xLVbmz0wa99tr3jJXCyWlqkSvSESRYxOlLan35UikRWjkU6MFihcmbnxtFfQHORqF5K+DK/X1WwRnFRv7i8vYdQQKBgQDxQRhelQz46JtDc79ZWFpFIjowlwhXctw0KrrgKy62ZGTMwuQnyIklOr8j7E2nJTI/vx1CMKcKZIxrZ/agl9l3t9SCsCd13CWC0cTFYXnI8omKN/2DbyMVXfxzp9u4+chvvPdAXnPYDV8sYxFK13y7sC4N6+uNtKcS/1oIfse5iQKBgQDL/CZ9uPMWBehex+iPlv8C2slR5E0xLX6ZjE0U90aTrf1ifa+HYdI/C4AA9Z2nMOvFs+JgDLd7OH0XybLGAXY0zy+zjUsFmnfQ2p5muYZGtQxtsvdHuFckmOxKOrNEVjtdbBUucQEjNZQ9xIK3batVRPKUopg4zW44EeuAOb0MSQKBgGWiT7rgveNKUsZ6x5zDDNxdC/iWV+xHNh8/9RQk/PvXlWNxox5ja+tkMUvX6+rDT8TtJU1SI7zMGR/SX2LONc4qgns/7I/JW4AeEPA6HU0bZ/fzmHg7ZKNGweiTSYxGpjr0d5EFeXYGRBb18T3/Q8vp76zru4MqHMxzCKHVjxxJAoGBAJxJIKSKo5RoClU0DPaW1eM2BbD8njfjh2/VkulRW32ifNSNP4MWa6NqCDSz+ooybTIYVIUKuTlrWkxzeMlELXDgnMeQpb4xT0NxfJNv6XUbGd6ik9sbXYjosYFd4COnfexh9wiSBDEZx+5bNVucZvz5ynIe8Unz+1JySGEB29ohAoGBAOjPEnEE4h9BjSSjpVOx4rxJytmo/6af++he6zKciBV9jS2zcpe3AXRjUupakDK/lwWX0drjzSCmekLbNaM52ls7N1PSOYAGSBKl7w6cbLnGLhgJ30KydlT4+QLWsBAhHkJXUtD7WH5CjfZ5PuBdOC9PNmWctdrGepOi8E0cMn0T
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApRDP9pyQV8dhemSk9o/gbAQ3wy0DAChKUBgXDWQYBuCmC3TCUnGzeZB8rNBdJOcvlrBDht2LvRC3FxBdYEOnHFB8KVKQ27oPoVibnhwA2ZvQGCqJxY+pT/0Ub2ZA80dDbPTPG3jIYnhwE6ym5yycu1YKugKddVx/xr2Hp9sZjxyA7on7Rj8SekvtxtxIL2fIdKKN5t4cCEP4S6FJm/k4FWepGmGawra0lmTdiElaf8WUsSASG9OGszpYCHD1la70rlhK3CqxE6fl8Z6i8oBG6VYdrXqPXxlg1tQu9n+xXAxKIHxkSYaQndD5eaNW40F4uBkp/DTtLmlO092YB56wTQIDAQAB
  notify_url: http://106.52.179.221:9100/api/v1/alipay/alipay_notify_url
  return_url: http://localhost:63342/s-pay-mall-ddd-market/docs/dev-ops/nginx/html/index.html
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# SC 渠道配置 - 拼团对接渠道值
sc:
  group:
    buy:
      market:
        source: s01
        chanel: c01

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml